### ISSUE TITLE
Error during package install

### ISSUE THREAD

**Issue by Kr4k0w** [volitank/nala#60]
Hi, today I've tried to install a package, but I've receveid this error, how to solve this?

──────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────╮
│ /usr/lib/python3/dist-packages/nala/nala.py:378 in install                                                                                │
│                                                                                                                                           │
│   375 │   color_force: bool = COLOR,                                                                                                      │
│   376 ) -> None:                                                                                                                          │
│   377 │   """Install packages."""                                                                                                         │
│ ❱ 378 │   _install(pkg_names, ctx)                                                                                                        │
│   379                                                                                                                                     │
│   380                                                                                                                                     │
│   381 @nala.command(help=_("Remove packages."))                                                                                           │
│                                                                                                                                           │
│ ╭────────────────────────────── locals ──────────────────────────────╮                                                                    │
│ │         assume_yes = None                                          │                                                                    │
│ │        auto_remove = None                                          │                                                                    │
│ │        color_force = None                                          │                                                                    │
│ │                ctx = <click.core.Context object at 0x7faf620c51d0> │                                                                    │
│ │              debug = None                                          │                                                                    │
│ │    default_release = None                                          │                                                                    │
│ │      download_only = None                                          │                                                                    │
│ │        dpkg_option = []                                            │                                                                    │
│ │         fix_broken = None                                          │                                                                    │
│ │ install_recommends = None                                          │                                                                    │
│ │   install_suggests = None                                          │                                                                    │
│ │           man_help = None                                          │                                                                    │
│ │          pkg_names = ['gping']                                     │                                                                    │
│ │              purge = None                                          │                                                                    │
│ │           raw_dpkg = None                                          │                                                                    │
│ │   remove_essential = None                                          │                                                                    │
│ │             simple = None                                          │                                                                    │
│ │             update = None                                          │                                                                    │
│ │            verbose = None                                          │                                                                    │
│ ╰────────────────────────────────────────────────────────────────────╯                                                                    │
│                                                                                                                                           │
│ /usr/lib/python3/dist-packages/nala/nala.py:195 in _install                                                                               │
│                                                                                                                                           │
│   192 │   │   │   error.unmarked_error(nala_pkgs.user_explicit)                                                                           │
│   193 │                                                                                                                                   │
│   194 │   auto_remover(cache, nala_pkgs)                                                                                                  │
│ ❱ 195 │   get_changes(cache, nala_pkgs, "install")                                                                                        │
│   196                                                                                                                                     │
│   197                                                                                                                                     │
│   198 def remove_completion(ctx: typer.Context) -> Generator[str, None, None]:                                                            │
│                                                                                                                                           │
│ ╭────────────────────────── locals ──────────────────────────╮                                                                            │
│ │     broken = []                                            │                                                                            │
│ │      cache = <nala.cache.Cache object at 0x7faf620c9160>   │                                                                            │
│ │        ctx = <click.core.Context object at 0x7faf620c51d0> │                                                                            │
│ │  not_exist = []                                            │                                                                            │
│ │  not_found = []                                            │                                                                            │
│ │  pkg_names = ['gping']                                     │                                                                            │
│ │ ver_failed = False                                         │                                                                            │
│ ╰────────────────────────────────────────────────────────────╯                                                                            │
│                                                                                                                                           │
│ /usr/lib/python3/dist-packages/nala/install.py:489 in get_changes                                                                         │
│                                                                                                                                           │
│    486 │   if arguments.raw_dpkg:                                                                                                         │
│    487 │   │   term.restore_locale()                                                                                                      │
│    488 │                                                                                                                                  │
│ ❱  489 │   download_pkgs(pkgs)                                                                                                            │
│    490 │   start_dpkg(cache, nala_pkgs)                                                                                                   │
│    491 │   write_history(cache, nala_pkgs, operation)                                                                                     │
│    492                                                                                                                                    │
│                                                                                                                                           │
│ ╭─────────────────────────────────────────────────── locals ────────────────────────────────────────────────────╮                         │
│ │     cache = <nala.cache.Cache object at 0x7faf620c9160>                                                       │                         │
│ │ nala_pkgs = PackageHandler(                                                                                   │                         │
│ │             │   autoremoved=set(),                                                                            │                         │
│ │             │   user_explicit=[<Package: name:'gping' architecture='amd64' id:97901>],                        │                         │
│ │             │   local_debs=[],                                                                                │                         │
│ │             │   not_needed=[],                                                                                │                         │
│ │             │   delete_pkgs=[],                                                                               │                         │
│ │             │   install_pkgs=[                                                                                │                         │
│ │             │   │   NalaPackage(name='gping', version='1.19.0-2', size=1100308, old_version=None)             │                         │
│ │             │   ],                                                                                            │                         │
│ │             │   reinstall_pkgs=[],                                                                            │                         │
│ │             │   upgrade_pkgs=[],                                                                              │                         │
│ │             │   autoremove_pkgs=[],                                                                           │                         │
│ │             │   autoremove_config=[],                                                                         │                         │
│ │             │   delete_config=[],                                                                             │                         │
│ │             │   recommend_pkgs=[],                                                                            │                         │
│ │             │   suggest_pkgs=[],                                                                              │                         │
│ │             │   configure_pkgs=[],                                                                            │                         │
│ │             │   downgrade_pkgs=[],                                                                            │                         │
│ │             │   held_pkgs=[]                                                                                  │                         │
│ │             )                                                                                                 │                         │
│ │ operation = 'install'                                                                                         │                         │
│ │      pkgs = [<Package: name:'gping' architecture='amd64' id:97901>]                                           │                         │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                         │
│                                                                                                                                           │
│ /usr/lib/python3/dist-packages/nala/downloader.py:922 in download_pkgs                                                                    │
│                                                                                                                                           │
│   919                                                                                                                                     │
│   920 def download_pkgs(pkgs: Iterable[Package]) -> None:                                                                                 │
│   921 │   """Download package from a list of pkgs."""                                                                                     │
│ ❱ 922 │   download(                                                                                                                       │
│   923 │   │   Downloader(                                                                                                                 │
│   924 │   │   │   # Start the larger files first, as they take the longest                                                                │
│   925 │   │   │   sorted(                                                                                                                 │
│                                                                                                                                           │
│ ╭──────────────────────────── locals ────────────────────────────╮                                                                        │
│ │ pkgs = [<Package: name:'gping' architecture='amd64' id:97901>] │                                                                        │
│ ╰────────────────────────────────────────────────────────────────╯                                                                        │
│                                                                                                                                           │
│ /usr/lib/python3/dist-packages/nala/downloader.py:889 in download                                                                         │
│                                                                                                                                           │
│   886 │   Does not return if in Download Only mode.                                                                                       │
│   887 │   """                                                                                                                             │
│   888 │   try:                                                                                                                            │
│ ❱ 889 │   │   run(downloader.start_download())                                                                                            │
│   890 │   except (CancelledError, RuntimeError) as error:                                                                                 │
│   891 │   │   if downloader.exit:                                                                                                         │
│   892 │   │   │   sys.exit(downloader.exit)                                                                                               │
│                                                                                                                                           │
│ ╭────────────────────────────── locals ──────────────────────────────╮                                                                    │
│ │ downloader = <nala.downloader.Downloader object at 0x7faf620c97f0> │                                                                    │
│ ╰────────────────────────────────────────────────────────────────────╯                                                                    │
│                                                                                                                                           │
│ /usr/lib/python3.13/asyncio/runners.py:195 in run                                                                                         │
│                                                                                                                                           │
│   192 │   │   │   "asyncio.run() cannot be called from a running event loop")                                                             │
│   193 │                                                                                                                                   │
│   194 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                                                                  │
│ ❱ 195 │   │   return runner.run(main)                                                                                                     │
│   196                                                                                                                                     │
│   197                                                                                                                                     │
│   198 def _cancel_all_tasks(loop):                                                                                                        │
│                                                                                                                                           │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                                                         │
│ │        debug = None                                                           │                                                         │
│ │ loop_factory = None                                                           │                                                         │
│ │         main = <coroutine object Downloader.start_download at 0x7faf6224cdc0> │                                                         │
│ │       runner = <asyncio.runners.Runner object at 0x7faf620c96a0>              │                                                         │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                                                         │
│                                                                                                                                           │
│ /usr/lib/python3.13/asyncio/runners.py:118 in run                                                                                         │
│                                                                                                                                           │
│   115 │   │                                                                                                                               │
│   116 │   │   self._interrupt_count = 0                                                                                                   │
│   117 │   │   try:                                                                                                                        │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                                                              │
│   119 │   │   except exceptions.CancelledError:                                                                                           │
│   120 │   │   │   if self._interrupt_count > 0:                                                                                           │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                                                          │
│                                                                                                                                           │
│ ╭─────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x7faf63376780>                                                                      │ │
│ │           coro = <coroutine object Downloader.start_download at 0x7faf6224cdc0>                                                       │ │
│ │           self = <asyncio.runners.Runner object at 0x7faf620c96a0>                                                                    │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of <asyncio.runners.Runner object at 0x7faf620c96a0>>,             │ │
│ │                  main_task=<Task finished name='Task-1' coro=<Downloader.start_download() done, defined at                            │ │
│ │                  /usr/lib/python3/dist-packages/nala/downloader.py:399> exception=TypeError("AsyncClient.__init__() got an unexpected │ │
│ │                  keyword argument 'proxies'")>)                                                                                       │ │
│ │           task = <Task finished name='Task-1' coro=<Downloader.start_download() done, defined at                                      │ │
│ │                  /usr/lib/python3/dist-packages/nala/downloader.py:399> exception=TypeError("AsyncClient.__init__() got an unexpected │ │
│ │                  keyword argument 'proxies'")>                                                                                        │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                                           │
│ /usr/lib/python3.13/asyncio/base_events.py:719 in run_until_complete                                                                      │
│                                                                                                                                           │
│    716 │   │   if not future.done():                                                                                                      │
│    717 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')                                                      │
│    718 │   │                                                                                                                              │
│ ❱  719 │   │   return future.result()                                                                                                     │
│    720 │                                                                                                                                  │
│    721 │   def stop(self):                                                                                                                │
│    722 │   │   """Stop running the event loop.                                                                                            │
│                                                                                                                                           │
│ ╭─────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<Downloader.start_download() done, defined at                                            │ │
│ │            /usr/lib/python3/dist-packages/nala/downloader.py:399> exception=TypeError("AsyncClient.__init__() got an unexpected       │ │
│ │            keyword argument 'proxies'")>                                                                                              │ │
│ │ new_task = False                                                                                                                      │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                                                             │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                                           │
│ /usr/lib/python3/dist-packages/nala/downloader.py:404 in start_download                                                                   │
│                                                                                                                                           │
│   401 │   │   if not self.pkg_urls:                                                                                                       │
│   402 │   │   │   return True                                                                                                             │
│   403 │   │   with Live(get_renderable=self._gen_table, refresh_per_second=10) as self.live:                                              │
│ ❱ 404 │   │   │   async with AsyncClient(                                                                                                 │
│   405 │   │   │   │   timeout=20,                                                                                                         │
│   406 │   │   │   │   proxies=self.proxy,                                                                                                 │
│   407 │   │   │   │   follow_redirects=True,                                                                                              │
│                                                                                                                                           │
│ ╭─────────────────────────── locals ───────────────────────────╮                                                                          │
│ │ self = <nala.downloader.Downloader object at 0x7faf620c97f0> │                                                                          │
│ ╰──────────────────────────────────────────────────────────────╯                                                                          │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

**Comment by onefish2** [comment]
I am seeing the same issue on 7 Ubuntu 25.04 VMs on my Proxmox host. This started when I upgraded them to 25.04 from 24.10.

**Comment by botus99** [comment]
I am also getting this error using nala v0.15.4 and apt v2.9.33 on Debian Testing. Started getting this error a few days ago.

**Comment by onefish2** [comment]
Forgot to mention. I was seeing this same error on Debian Trixie for the past few weeks as well.

**Comment by Cisien** [comment]
I see this on Debian SID as well

**Comment by botus99** [comment]
### UPDATE: This fixed it for me...
original comment from [gitlab](https://gitlab.com/volian/nala/-/issues/343)

> Daltux@daltux 
> Changing /usr/lib/python3/dist-packages/nala/downloader.py line 406 indeed fixes the issue on Debian "trixie/sid".
> The diff is:
> 
> ```
> user@host:/usr/lib/python3/dist-packages/nala$ diff downloader.py.bak downloader.py
> 406c406
> < 				proxies=self.proxy,
> ---
> > 				mounts=self.proxy,
> ```
> 
> Let's hope the package is soon updated on Debian repository anyway.
> Thank you very much for the tip!

I simply changed /usr/lib/python3/dist-packages/nala/downloader.py at line 406 to `mounts=self.proxy`. Boom, nala works again.

**Comment by onefish2** [comment]
Awesome. Thanks for sharing!

**Comment by Desmo5574** [comment]
Running Debian Sid/trixie and have had his this problem for the past 3 weeks or so. The fix from @botus99 did the trick for me. 
Back to using my beloved nala again...

**Comment by iller7** [comment]
Thank you for this, much appreciated!

**Comment by QinCai-rui** [comment]
Thanks! had the same issue on Ubuntu 25.05! interestingly, `nala` was working on Trixie for me

**Comment by QinCai-rui** [comment]
closing this https://github.com/volitank/nala/issues/66

**Comment by yscialom** [comment]
It appears this issue is fixed on the current version.

[`nala/nala/downloader.py` on `main`](https://github.com/volitank/nala/blob/main/nala/downloader.py#L410C8-L410C23):
```python
		with Live(get_renderable=self._gen_table, refresh_per_second=10) as self.live:
			async with AsyncClient(
				timeout=20,
				mounts=self.proxy,
				follow_redirects=True,
```

Blame points to [`e12ce19` "fix(downloader): proxies deprecation" 2025-03-19](https://github.com/volitank/nala/commit/e12ce19c44ad96b1a3542744a196612025970985).

I suggest to close this issue.

**Comment by OS-Scratch** [comment]
> `mounts=self.proxy`

Thanks! The same error on Ubuntu, now I can install packages again!

**Comment by volitank** [comment]
This GitHub repository is a mirror and issues are not tracked here.

If this is still an issue, please report it on the canonical GitLab repository:
https://gitlab.com/volian/nala/-/issues

Thanks!
